### ISSUE TITLE
Add paribhASA

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#11]
See the appendices of SK regarding paribhASAs and add some markup to identify them in sk0.txt.

**Comment by drdhaval2785** [comment]
Added all paribhASAs into branch paribhasha.
https://github.com/drdhaval2785/siddhantakaumudi/commits/paribhasha

Also regenerated XML based on it.
https://github.com/drdhaval2785/siddhantakaumudi/commit/1144665cc1a6de4f280f802ed00bde50d49ef33c#diff-9a45b25ec62a6582a9756f55ae90284bR329
e.g.
```
 <div type="paribhāṣā"> परनित्यान्तरङ्गापवादानामुत्तरोत्तरं बलीयः</div> ॥ <div type="paribhāṣā"> असिद्धं बहिरङ्गमन्तरङ्गे</div> ॥ <div type="paribhāṣā"> अकृतव्यूहाः पाणिनीयाः</div> ॥
```
@kmadathil 
Once you incorporate this paribhāṣā tag into your HTML side, we will release a new version.
Time to regenerate epub 👍

**Comment by drdhaval2785** [comment]
encoding and extraction over from my side.

**Comment by kmadathil** [comment]
@drdhaval2785 - Noted, it may take me a day or two to get going on this.

**Comment by kmadathil** [comment]
What would be a good way of displaying paribhaasha so they are distinct from vaartika? I was thinking of underlines, does that sound ok?

**Comment by drdhaval2785** [comment]
What would be a good way of displaying paribhaasha so they are distinct
from vaartika? I was thinking of underlines, does that sound ok?

I feel we should not keep the choices static. Instead of italics for
vartikas and underlines for paribhashas, making such changes in a CSS makes
it much more flexible.

Maybe something like `div type="vArtika"` or `span type="vArtika"` and then
in CSS colour it grey.

Excuse non diacritic typing. I m typing from phone.

**Comment by kmadathil** [comment]
> Excuse non diacritic typing. I m typing from phone.
 :-) I'd rather just type ad-hoc or use devanagari.

 paribhāṣā tags have been added.
 Embedded css has been used to style the following elements - sutra, dhatu, vartika, paribhasha. All have tooltips that identify their class.
