### ISSUE TITLE
add pratyAhAra description

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#12]
pratyAhAra description is missing. Add manually.

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/siddhantakaumudi/commit/13089b12481d4c2fcfa508d921b4abf5a87ab812 completed this task.
Data added in sk0.txt

maGgalAcaraNam given id 0 and link 0-0-0
pratyAhAra given id 00 and link 0-0-1

Maybe we will have to hide these two links in HTML display. @kmadathil .
There actually are no such sUtras.

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/siddhantakaumudi/commit/4923d0fd375a15ebd49874155f5b60aa4cc381f4 did regeneration of HTML and epub.

**Comment by kmadathil** [comment]
Removed AVG links for 0-0-0 and 0-0-1
