### ISSUE TITLE
Let users see the latest sk.html as a web page.

### ISSUE THREAD

**Issue by vvasuki** [drdhaval2785/siddhantakaumudi#13]
One can use https://pages.github.com/  to let users view the latest sk.html as a proper web page (not a text file). This will help readers greatly!

**Comment by gasyoun** [comment]
> sk.html as a proper web pag

Sure!  Why are there 3978 rules, so an amount lesser than Panini, or it's because of the Shiva sutras not added here?

**Comment by kmadathil** [comment]
I have made the following changes in my fork: 

-    moved sk.{html,epub} to the docs/ directory
-    added docs/index.html as a symlink to sk.html
-    changed settings to build pages from the docs directory

https://kmadathil.github.io/siddhantakaumudi/ is now visible. 
I will send a pull request for these changes. (The settings change must be made in this repo independently)

**Comment by drdhaval2785** [comment]
@kmadathil

I would like to add you as a collaborator in this repository itself so that you need not work on your fork and send PR.
Let me know if this sounds good to you.

**Comment by drdhaval2785** [comment]
@vvasuki the site is live at https://drdhaval2785.github.io/siddhantakaumudi/.
Thanks for suggestion.

**Comment by kmadathil** [comment]
@drdhaval2785
Please do that. Thanks.
