### ISSUE TITLE
sUtra detail when hovering over link

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#16]
![capture](https://cloud.githubusercontent.com/assets/5755132/22701689/5c7a82f6-ed84-11e6-898b-42edb88d663d.png)

@kmadathil 
It would be great if I can see the sUtra text when I hover mouse over the link.
In present case when I hover my mouse over 252, I would love to see 'हल्ङ्‍याब्भ्यो सुतिस्यपृक्तं हल्‌' as title (tooltip).

**Comment by kmadathil** [comment]
Implemented in branch karthik.
Not merging in master because of TEI changes in progress

**Comment by kmadathil** [comment]
Merged

**Comment by drdhaval2785** [comment]
Great work @kmadathil.
