### ISSUE TITLE
External links to open in new tab

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#17]
@kmadathil 
Currently when I click on an external link (avg link), it loads in the same tab.
It would be great if I remain on the same page and the link opens in another tab by default.

`target="_blank"` maybe. I am not sure about HTMLs.

**Comment by gasyoun** [comment]
target="_blank" indeed in a href.

**Comment by kmadathil** [comment]
Implemented in branch karthik.
Not merging in master because of TEI changes in progress

**Comment by kmadathil** [comment]
Merged.
