### ISSUE TITLE
New branch for TEI changes?

### ISSUE THREAD

**Issue by kmadathil** [drdhaval2785/siddhantakaumudi#18]
@drdhaval2785 
Not sure how far you are on the TEI vector, but would it be possible for you to move that work to a new branch and move master back to hash de38856? I can then merge the tooltip changes. 
Work on TEI tagging/XSLT changes can go on in parallel in a new branch without affecting master and can be merged once we're happy with results.

**Comment by drdhaval2785** [comment]
I am looking forward to complete TEI changes by latest tomorrow. Then there
shall not be much changes in XML structure. If possible, please bear with
me till such time.

I never tried working on branches. Thats my only glitch.

**Comment by kmadathil** [comment]
Sure, no problem.

Next time there's a major feature planned, let's use a branch so we keep
master always consistent (which is the recommended workflow with git). This
is how to do it

In your local repo
`git checkout -b <feature_name>` (Create local branch for feature from
master and switch to it)
Work
`git commit`
`git push origin <feature_name>` (Push to remote, create a remote branch
for feature)
Work
`git commit`
Work
`git commit`
`git push`
...
Once work is consistent
`git commit`
`git push` (Strictly not required, but for safety)
`git checkout master` (Switch back to master)
`git merge <feature_name>`  (merges work into master once it's consistent)
`git push`   (push to remote master)
`git push origin --delete <feature_name>`  (delete remote branch for
feature)
`git branch -d <feature_name>` (delete local branch for feature)
