### ISSUE TITLE
Add dhaatu meanings in the dhaatu index

### ISSUE THREAD

**Issue by kmadathil** [drdhaval2785/siddhantakaumudi#19]
Currently, dhaatu meanings do not appear in the index. Fix XSLT so that they appear.

**Comment by drdhaval2785** [comment]
@kmadathil 
Not only in dhaatu index, but also in HTML also please.

Something like
`<span type="dhātvarthaḥ"><span id="D6">6 <b>नाथृ</b></span> <span id="D7">7 <b>नाधृ</b></span> याच्ञोपतापैस्वर्याशीःषु </span>` or something similar.

Suggestion in https://github.com/drdhaval2785/siddhantakaumudi/issues/6#issuecomment-279192953 is also incorporated in this comment. 
So closing that issue once again.

**Comment by drdhaval2785** [comment]
@kmadathil 
Once this issue is resolved, we are ready for v1.2.0 (Main addition being verb data capture and display).
Changelog already prepared in XML and HTML.

**Comment by kmadathil** [comment]
Added dhaatu numbers back into HTML
Fixed the issue of dhaatu meanings not appearing in index
