### ISSUE TITLE
Use other sources to identify sUtramUlam errors

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#2]
Use other available AS sUtramUlam lists to see that the data of SK sUtramUlam is correct.

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/siddhantakaumudi/blob/issue2/issues/test.txt

This file has hints to the headword corrections.

Format
e.g.
```
line in sk1.txt where supposed error is
suggested reading. 
```
E.g.
```
; {#131#} ङः सि धुट् {@8-3-29@}
डः सि धुट्
```

**Comment by drdhaval2785** [comment]
Total 600 such entries.
Need some normalization further to trim the entries like
; {#192#} एकवचनं सम्बुद्धिः {@2-3-49@}
एकवचनं संबुद्धिः

Only difference here is in m / M.

**Comment by gasyoun** [comment]
> Only difference here is in m / M.

How familiar.

**Comment by drdhaval2785** [comment]
Changes merged into master branch.

Keeping this issue open. 

This may require a further revisit before it may be termed stable.

**Comment by drdhaval2785** [comment]
This seems to be done task. If anything is missed out, it will be caught in bigram trigrams.
