### ISSUE TITLE
Noticed some untagged dhAtus?

### ISSUE THREAD

**Issue by kmadathil** [drdhaval2785/siddhantakaumudi#20]
For example 
10 श्विदि श्वैत्ये

**Comment by drdhaval2785** [comment]
I think I know where it went wrong.
There were some typo errors in sk0.txt (base text) which were corrected in sk1.txt by a script.
Most notable were श्र्व -> श्व, ञ्ञ -> ञ and ःढ़द्य;->ऊ.
Therefore the logic went somewhere haywire while dealing with these particular letters.
https://github.com/drdhaval2785/siddhantakaumudi/blob/master/step1.py#L95
https://github.com/drdhaval2785/siddhantakaumudi/blob/master/step1.py#L101
https://github.com/drdhaval2785/siddhantakaumudi/blob/master/step1.py#L102

I will need to fix this logic.
I guess all verbs having any of these letters will be missed in tagging.

Regex captures them, but I do a replacement. The data in sk0.txt and sk1.txt have different items so they are not replaced.

@kmadathil Thanks for such minute observation.

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/siddhantakaumudi/commit/b42d15d342d5311332d6503b8c82733850f8bbc5 closed this issue.
If any further observations come your way, please raise a new issue.
