### ISSUE TITLE
Added Licence and Source descriptions to XSLT - Please check

### ISSUE THREAD

**Issue by kmadathil** [drdhaval2785/siddhantakaumudi#22]
@drdhaval2785 
I have added code in XSLT to extract Licence and Source descriptions. Please check if the output is ok by you.

**Comment by drdhaval2785** [comment]
Seems great

**Comment by gasyoun** [comment]
What Licence?

**Comment by kmadathil** [comment]
@gasyoun 
The XML refers to https://creativecommons.org/licenses/by-sa/4.0/ 
The HTML now reproduces this.

**Comment by gasyoun** [comment]
Oh, @kmadathil thanks. I mean for me what is important that  it's open. For some even CC 4.0 is not enough, and they ask for https://www.gnu.org/licenses/gpl-3.0.en.html or MIT.

**Comment by kmadathil** [comment]
@gasyoun , since @drdhaval2785 's is the encoder, I'll let him comment on CC vs MIT.

**Comment by gasyoun** [comment]
Sure, just to make you aware that for some (out of the 5 coders around interested in Sanskrit NLP), that's important.

**Comment by kmadathil** [comment]
@gasyoun - is there a summary of Open Sanskrit NLP work going on that I can look at? Just curious.

**Comment by drdhaval2785** [comment]
Went for GNU GPLv3.

**Comment by kmadathil** [comment]
The LICENSE has changed to GPLv3 but the text still says its available at the Creative Commons website instead of gnu.org
https://www.gnu.org/licenses/gpl-3.0.en.html

**Comment by kmadathil** [comment]
Also, the Attribution and Share Alike clauses are CC specfic, and would be better removed.

**Comment by drdhaval2785** [comment]
Ok.

**Comment by drdhaval2785** [comment]
@kmadathil 
Removed CC remnants.
Also there was one error in tagging the weblink which led to the whole line being hyperlinked.
![capture](https://cloud.githubusercontent.com/assets/5755132/23981625/fee838f6-0a2d-11e7-8972-76cb13e16086.png)

Corrected that as well. 
So you can regenerate HTML and see whether it forms well.

**Comment by drdhaval2785** [comment]
@kmadathil 
Removed CC remnants.
Also there was one error in tagging the weblink which led to the whole line being hyperlinked.

Corrected that as well. 
So you can regenerate HTML and see whether it forms well.

**Comment by drdhaval2785** [comment]
I will let you close when you are OK with the output and all changes are reflected in HTML properly.

**Comment by gasyoun** [comment]
@kmadathil none documented, but whait, @vvasuki has the best documentation out there, ask him.

**Comment by kmadathil** [comment]
@drdhaval2785 
Can you change the license link to https://www.gnu.org/licenses/gpl-3.0.en.html

It currently points to  https://www.gnu.org/licenses/quick-guide-gplv3.html 
I think we should point to the license directly.

**Comment by vvasuki** [comment]
@drdhaval2785 - Why did you go with GPL? From what I recall, it restricts use of software for closed source purposes. Why not go with something broader like just - creative commons attribution?

@gasyoun @kmadathil Well, regarding summary, there isn't much - but there is this rather informal and outdated page - https://sites.google.com/site/sanskritcode/home/survey

**Comment by drdhaval2785** [comment]
I feel that fruit of open source labour should also be open source. Thats
why.

**Comment by kmadathil** [comment]
@vvasuki - Thanks!

@drdhaval2785 - Perhaps we can release all our scripts and XSLT under GPLv3 or MIT licenses (retaining the right to relicence under other licenses) but release the XML/HTML/EPUB and text sources under CC4.0-BY-SA?

**Comment by drdhaval2785** [comment]
I am not very good at choosing licence and their pros and cons.
Can @kmadathil or @vvasuki or @gasyoun mention the pros and cons of various licences that float around ? Or some tutorial link to the same effect?

**Comment by vvasuki** [comment]
> Can @kmadathil or @vvasuki or @gasyoun mention the pros and cons of various licences that float around ? Or some tutorial link to the same effect?

One important dimension of difference is whether closed commercial apps can use your programs. MIT allows that, GNU doesn't. My personal bias is to encourage as much reuse (even within closed source) as possible where it comes to sanskrit (as it is companies are not interested in developing sanskrit language features - why make it harder).

> @drdhaval2785 - Perhaps we can release all our scripts and XSLT under GPLv3 or MIT licenses (retaining the right to relicence under other licenses) but release the XML/HTML/EPUB and text sources under CC4.0-BY-SA?

I'd suggest MIT for your scripts and xslt, and use C4.0-BY-SA for XML/HTML/EPUB - but have no license whatever for the text (you can't enforce it - and it belongs to shrI bhaTToji anyway).

**Comment by gasyoun** [comment]
> it belongs to shrI bhaTToji anyway

As an etext it does not. So MIT is a good go.

**Comment by kmadathil** [comment]
> My personal bias is to encourage as much reuse (even within closed source) as possible where it comes to sanskrit (as it is companies are not interested in developing sanskrit language features - why make it harder).

Makes sense. Therefore, we should aim at preserving our basic rights to use, modify and share this, while not limiting someone's ability to use this in commercial or closed source applications.

> I'd suggest MIT for your scripts and xslt, and use C4.0-BY-SA for XML/HTML/EPUB - but have no license whatever for the text (you can't enforce it - and it belongs to shrI bhaTToji anyway).

Since the XML/HTML/EPUB are generated from our scripts, it's sensible to not have them under a stronger restriction than the scripts themselves. Reading through the text, CC4.0-BY-SA is stronger than MIT, much closer to GPL3. CC4.0-BY looks more like MIT - it allows commercial derivatives as long as attribution is given. 

However, since XML/HTML is software, we can use MIT for that as well. 

@drdhaval2785 
This is the "MIT" License. Please review. We will need to add to the head of each script, as well as mention this in a LICENSE (or LICENCE) file
http://directory.fsf.org/wiki/License:Expat

This is the CC4.0-BY License. If we choose to use this for XML/HTML (my preference is MIT), we will need to add links to these in the XML/HTML and mention in the LICENSE file. 
https://creativecommons.org/licenses/by/4.0/

**Comment by drdhaval2785** [comment]
https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software
suggests against using CC to softwares.
So MIT uniformly all across seems reasonable to me.

**Comment by kmadathil** [comment]
@drdhaval2785  
Let's go with it then

**Comment by drdhaval2785** [comment]
https://opensource.org/licenses/MIT
