### ISSUE TITLE
epub regenetation to minimum

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#23]
As Git considers epub to be binary file and not a text based file, with every minor change in epub, some 700 kb need to be stored in git. With so many changes happenning in base files, I propose that we regenerate epub only when we release a new version with some feature addition etc. 

Whats your take @kmadathil?

700kb is not a big shot. But 500 commits with 700kb changes is.

**Comment by kmadathil** [comment]
I concur. I will not regenerate epub on any checkin except when a major release is to be made.
