### ISSUE TITLE
Include verb meaning inside span verb

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#26]
@kmadathil 
Please see the attached image.
Verb number and verb is included in bold, but meaning is not bold face.
It would be great to keep it inside span element.

![capture](https://cloud.githubusercontent.com/assets/5755132/22980978/112a3448-f3c1-11e6-853e-3f44a4d2056e.png)

**Comment by kmadathil** [comment]
Done
