### ISSUE TITLE
Siddhanta font

### ISSUE THREAD

**Issue by gasyoun** [drdhaval2785/siddhantakaumudi#27]
Why not use a web font with ligatures?

![siddhantaa](https://cloud.githubusercontent.com/assets/80761/23105181/ccfb2d08-f6eb-11e6-9f7e-4fe4147424fd.PNG)

**Comment by drdhaval2785** [comment]
@kmadathil 
What @gasyoun wants to convey is to have Siddhanta font in font-family .... etc in the CSS itself.
That will ensure that it is displayed in Siddhanta font in case it is installed in machine.
Gives much better rendering than with Shruti or Mangal unicode default fonts for ligatures.

**Comment by kmadathil** [comment]
Done. CSS Now has 
 body {
	   font-family: Siddhanta;
	  }

I have Siddhanta installed on my machine, and I can see the html in Siddhanta without setting it in Chrome.

**Comment by gasyoun** [comment]
> I can see the html in Siddhanta without setting it in Chrome.

Even before?
