### ISSUE TITLE
Underlined text

### ISSUE THREAD

**Issue by gasyoun** [drdhaval2785/siddhantakaumudi#28]
Why is it underlined in 214?

![214](https://cloud.githubusercontent.com/assets/80761/23105188/f1994b0e-f6eb-11e6-80e5-1c4b8788235d.PNG)

**Comment by drdhaval2785** [comment]
Paribhasha my friend.. hover over it. It will tell you it is paribhASa.

**Comment by gasyoun** [comment]
> Paribhasha

Is it mentioned anywhere on the page?

And what's italics?

**Comment by kmadathil** [comment]
@gasyoun Hover over a phrase that's highlighted in any way, and you should see a tooltip that tells you why. 
I will add a key table summarizing the highlights as requested in issue #31 so that it's clear.

**Comment by gasyoun** [comment]
@kmadathil `key table summarizing` - thanks!

**Comment by kmadathil** [comment]
First appendix is now a table of display highlights
