### ISSUE TITLE
Wrong order of characters

### ISSUE THREAD

**Issue by gasyoun** [drdhaval2785/siddhantakaumudi#30]
फि29: स्वाङ्गशिटामदन्तानाम्‌ (10-2-29)
्शिट्‌ सर्वनाम । 'कर्णा॑भ्या॒ं चुबु॑का॒दधि॑' । 'विश्वो॒ विहा॑य ॥

![bad nagari](https://cloud.githubusercontent.com/assets/80761/23105359/0f651994-f6ef-11e6-8ddd-d552ecd77fcc.PNG)

**Comment by gasyoun** [comment]
फि75 -> फि 75

**Comment by drdhaval2785** [comment]
फि29: स्वाङ्गशिटामदन्तानाम्‌ (10-2-29)
्शिट्‌ सर्वनाम । 'कर्णा॑भ्या॒ं चुबु॑का॒दधि॑' । 'विश्वो॒ विहा॑य ॥


Unicode is crazy. Order is proper. Accent is always after vowel. Not after
anusvAra.

**Comment by drdhaval2785** [comment]
फि75 -> फि 75

Leave it. They are tag markers to a sUtra. A space in between means a lot
of problems in processing and regex. A conscious decision was taken at the
cost of readability.

**Comment by gasyoun** [comment]
> A space in between means a lot
of problems in processing and regex.

A bad regexer.

> Unicode is crazy. 

But it's fixable, had similar issues myself once.

**Comment by drdhaval2785** [comment]
After changing to Siddhanta - it is gone.

![capture](https://cloud.githubusercontent.com/assets/5755132/23736188/8c006bb0-04b0-11e7-8947-bef93424d04d.png)

**Comment by gasyoun** [comment]
> After changing to Siddhanta - it is gone.

Good news.
