### ISSUE TITLE
AS sUtra numbering errors

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#35]
(2182)अभ्यासे चर्च    7-4-54 
अभ्यासे झलां चरः स्युर्जशश्च। झशां जशः खयां चरः। तत्रापि प्रकृतिजशां प्रकृतिजशः प्रकृतिचरां प्रकृतिचर इति विवेक आन्तरतम्यात्।।

Here the rule is actually 8-4-54 and not 7-4-54.

This shows that there may be other errors of sUtra numbers as well.

There is a logical way of finding such abberrant behaviours.
1. Create a dict having sutra number as key and sutra text as value out of SK data.
2. Create a dict having sutra number as key and sutra text as value out of AS data (available [here](https://github.com/drdhaval2785/SanskritVerb/blob/master/scripts/function.php#L138))
3. Compare the edit distance. If edit distance is greater than 3, it means some error in marking.
4. Gross difference will mean that numbering in either of it is bad.

Known issue - there may be some numbering differences between editions.

**Comment by drdhaval2785** [comment]
Another instance
; {#2679#} भावकर्मणोः {@1-2-13@}
वा गमः

Actually 1-3-13

**Comment by drdhaval2785** [comment]
; {#2764#} भञ्चेश्च चिणि {@6-4-63@}
दीङो युडचि क्ङिति

Actually 6-4-33

**Comment by gasyoun** [comment]
> Known issue - there may be some numbering differences between editions.

This is where the fun starts. Especially in comparing different editions of Mahabharata, I tell you.

**Comment by drdhaval2785** [comment]
; {#2764#} भञ्चेश्च चिणि {@6-4-63@}
दीङो युडचि क्ङिति

Actually 6-4-33

**Comment by drdhaval2785** [comment]
Duplicate numbers are as follows, which need some correction.
```
8-2-85 
7-1-94 
8-2-72 
1-4-21 
6-3-23 
6-4-138 
4-1-178 
4-1-70 
4-2-31 
4-2-5 
7-3-19 
5-1-80 
5-2-39 
5-2-16 
5-3-1 
5-2-57 
5-4-78 
5-3-94 
8-2-79 
3-1-35 
7-3-72 
2-4-34 
7-1-21 
8-2-35 
7-3-13 
6-4-4 
7-4-54 
7-3-94 
3-1-14 
3-1-29 
1-2-13 
6-4-63 
3-2-122 
3-4-99 
3-2-93 
7-2-42 
6-4-94 
8-4-24 
3-2-33 
1-4-8 
2-3-73 
3-1-42 
3-1-47 
5-4-148 
6-3-96 
6-3-108 
6-4-103 
7-1-103 
7-2-70 
7-4-62 
8-2-7 
8-2-1 
6-1-12 
8-3-49 
8-4-27 
1-3-38 
6-1-63 
6-1-176 
6-1-183 
6-2-67 
6-2-86 
6-2-88 
6-2-98 
```

**Comment by binghe** [comment]
8-2-85	S.96
7-1-94	S.276
8-2-72	S.334
1-4-21	S.187
6-3-23  S.981
6-4-138	S.416
4-1-178 S.1197
4-1-70  S.525
4-2-31 	S.1233
4-2-5   S.1206
7-3-19	S.1133
5-1-80  S.1744
5-2-39	S.1840
5-2-16	S.1817
5-3-1	S.1947
5-2-57	S.1857
5-4-78	S.946
5-3-94	S.2049
8-2-79	S.1629
3-1-35	S.2306
7-3-72	S.2337
2-4-34	S.351
7-1-21	S.372
8-2-35	S.2451
7-3-13	S.1399
6-4-4	S.300
7-4-54	S.2623
7-3-94	S.2651
3-1-14	S.2670
3-1-29	S.2422
1-2-13	S.2700
6-4-63	S.2507
3-2-122 S.2782
3-4-99	S.2200
3-2-93	S.3003
7-2-42	S.2528
6-4-94	S.2955
8-4-24	S.3294
3-2-33	S.2948
1-4-8	S.257
2-3-73	S.631
3-1-42	S.3403
3-1-47	S.2407
5-4-148 S.886
6-3-96	S.3529
6-3-108 S.3530
6-4-103 S.3553
7-1-103 S.3578
7-2-70	S.2366
7-4-62	S.2245
8-2-7	S.236
8-2-1	S.12
6-1-12	S.2586
8-3-49	S.3634
8-4-27	S.3649
1-3-38	S.2711
6-1-63	S.228
6-1-176 S.3722
6-1-183 S.3727
6-2-67	S.3801
6-2-86	S.3820
6-2-88	S.3822
6-2-98	S.3832

Above data is from the paper edition of «Ashṭādhyāyī of Pāṇini» translated by Śrīśa Chandra Vasu, reprinted in 2003. At the end of Volume II there's a full mapping from rule numbers in Ashṭādhyāyī (A) to Siddhanta Kaumudi (S). Unfortunately there're printing errors, and in about 10 cases the same S rule maps to more than one A rule. I could have corrected them using your work but haven't done it yet...

**Comment by drdhaval2785** [comment]
After corrections and rerun of script,
there are now only 4 such errors pending.
```
8-3-35 
8-1-72 
6-4-46 
6-3-92 
```

**Comment by drdhaval2785** [comment]
@binghe 
Thank you very much for your interest in Siddhantakaumudi.

>Unfortunately there're printing errors, and in about 10 cases the same S rule maps to more than one A rule

How did you know that there are about 10 cases? Visual inspection or some programmatic comparison? Is the data of AS appendices digitized?

**Comment by gasyoun** [comment]
> full mapping from rule numbers in Ashṭādhyāyī (A) to Siddhanta Kaumudi (S). Unfortunately there're printing errors

Was not aware of the errors.

**Comment by binghe** [comment]
@drdhaval2785  There're actually 26 cases, I have a FileMaker database holding the A-S mapping, and I can check duplicated or missing numbers by doing SQL-like operations. Now I think you have fixed all numbering issues. There 3978 S rules, while there're 3983 A rules, the following 5 A rules are not in Siddhanta Kaumudi: (but they context appears in commentary of other S rules):

4-1-166
4-1-167
6-1-62
6-1-100
6-1-136

(If you search above 5 A rule numbers in SK.html, you won't find them)

**Comment by binghe** [comment]
Yes, the data of AS appendices (only the A-S mapping) are digitized by me (in several days), then I use you SK.html to correct those duplicated and missing S numbers.

In attach, there're two Excel sheets (dumped from my FM database) with the same data but different sorting. It's the AS appendices with duplication and missing numbers corrected, according to SK.html, with rule text compared with http://avg-sanskrit.org/sutras).
[A-S.xlsx](https://github.com/drdhaval2785/siddhantakaumudi/files/835260/A-S.xlsx)
[S-A.xlsx](https://github.com/drdhaval2785/siddhantakaumudi/files/835261/S-A.xlsx)

**Comment by gasyoun** [comment]
> 3978 S rules, while there're 3983 A rules, the following 5 A rules are not in Siddhanta Kaumudi: (but they context appears in commentary of other S rules)

That's what I was missing.

![indexx](https://cloud.githubusercontent.com/assets/80761/23821185/e520e350-063b-11e7-9396-13c1d6d0e306.PNG)

links nowhere, otherwise it's
1) full
2) copypastable
3) Unicode
What else can one wish?
4) extract and add French translation from http://www.taralabalu.org/panini/ and OCR German from Boethlingk.
