### ISSUE TITLE
Add appendices to HTML

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#40]
The dhAtusUci is quite impressive.
@kmadathil 
It would be great if we have the following appendices.
1. sUtras sorted alphabetically.
2. sUtras sorted in Ashtadhyayi order
3. vArtikas sorted alphabetically.
4. paribhASAs sorted alphabetically.
5. uNAdisUtras sorted alphabetically.
6. phiTsUtras sorted alphabetically.
7. ~~dhAtusUci sorted alphabetically.~~

These should be easily extractable items. 
Some XSLT magic will make it happen I guess.
What is your say ?

**Comment by kmadathil** [comment]
@drdhaval2785 
All of these are doable. I'll work on this, give me a few days.

**Comment by drdhaval2785** [comment]
Take your own time. Just jotting down points as they occur to me.

**Comment by gasyoun** [comment]
@drdhaval2785 no reverse sorting?

**Comment by drdhaval2785** [comment]
No requirement at all.

**Comment by drdhaval2785** [comment]
@kmadathil,
still on radar?

**Comment by kmadathil** [comment]
Very much, just stuck with work for a few days. ETA of these is end of next
week.

**Comment by kmadathil** [comment]
Done in 46fdc1b. Please check.

sUtras sorted in Ashtadhyayi order needs some work over what I have. The current sort is a string sort, which results in the wrong order. I will open a different bug for that. 

In the appendices, paribhAShA and vArtika are linked to the sutra_with_explanation context which quotes them

**Comment by kmadathil** [comment]
Issue 50 (sUtras sorted in Ashtadhyayi order) is now fixed in 370cb0c
@drdhaval2785 , please close if the appendixes are good enough.

**Comment by drdhaval2785** [comment]
This fruitful issue has come to an end.
Kudos @kmadathil.

Noted very minor correction issues separately.
Closing this issue.

**Comment by kmadathil** [comment]
Thank you @drdhaval2785
