### ISSUE TITLE
missing verbs in sk.xml

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#44]
1502
1509
1209
1784-1800

There is some algo going haywire somewhere. It may be in XML or not. Need examination.

**Comment by drdhaval2785** [comment]
1209 is absent in the original texts all throughout.
Rest all corrected.

**Comment by drdhaval2785** [comment]
There is one missing in 1168.
Whatever we do, we can not tally numbers.
![capture](https://cloud.githubusercontent.com/assets/5755132/23829078/88ec5cc8-070c-11e7-9c71-ab0cc3b723f1.png)

I tried correcting the numbers till 1208, but realized the futility later on.
So Right now 1168 to 1208 are a bit misnumbered from print.

**Comment by gasyoun** [comment]
> So Right now 1168 to 1208 are a bit misnumbered from print.

a bit :1234:
