### ISSUE TITLE
च्छndasi 

### ISSUE THREAD

**Issue by kmadathil** [drdhaval2785/siddhantakaumudi#46]
3403: अभ्युत्सादयांप्रजनयांचिकयांरमयामकःपावयांक्रियाद्विदामक्रन्निति च्छndasi (3-1-42)
(noticed accidentally)

**Comment by drdhaval2785** [comment]
Strange. This calls for examination of Roman alphabets in whole text. Roman letters are not possible. Special chars and numbers can exist.

**Comment by drdhaval2785** [comment]
This is sole such entry. Closed issue.

**Comment by gasyoun** [comment]
> Roman letters are not possible.

Impossible, but true.
