### ISSUE TITLE
sutra links for phiT and uNaadi sutras are broken.

### ISSUE THREAD

**Issue by kmadathil** [drdhaval2785/siddhantakaumudi#47]
फि1: फिषोऽन्त उदात्तः (10-1-1)
उ1: कृवापाजिमिस्वदिसाध्यशूभ्य उण् (9-1-1)

@drdhaval2785 
Do we just hide the links (as we've done for 0-x-x), or is there a definitive site we can link to that describes these?

**Comment by drdhaval2785** [comment]
Hide. There are no sites for uNAdi or phiT

**Comment by kmadathil** [comment]
Ok, will do that.

**Comment by kmadathil** [comment]
Fixed
