### ISSUE TITLE
TEI tag change

### ISSUE THREAD

**Issue by kmadathil** [drdhaval2785/siddhantakaumudi#48]
&lt;TEI xml:id="Dhaval__SK" xmlns="http://www.tei-c.org/ns/1.0"&gt;
has now changed to 
&lt;TEI&gt;

This change affects XSLT (since the namespace of the tag has changed!). Is this intended to be an experiment or a fixed change? 

As of now, run_xslt results in incorrect output because of this. I will modify based on your answer, @drdhaval2785

**Comment by drdhaval2785** [comment]
Experimental basis. No need to change namespace. You can proceed with old
one.

**Comment by kmadathil** [comment]
No change in XSLT. Closing
