### ISSUE TITLE
1902: राजन्वान् सौराज्ये (9-2-14)

### ISSUE THREAD

**Issue by kmadathil** [drdhaval2785/siddhantakaumudi#49]
1902: राजन्वान् सौराज्ये (9-2-14)

Shouldn't this be 8-2-14?

**Comment by drdhaval2785** [comment]
Yes.
Wait a moment. I will recreate .xml afresh after taking both of your items into consideration.

**Comment by drdhaval2785** [comment]
xml regenerated
