### ISSUE TITLE
Add AS sUtra in सूत्राणि वर्णक्रमेण

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#52]
अकः सवर्णे दीर्घः 85 
to be changed to 
(6-1-101) अकः सवर्णे दीर्घः 85

In a way similar to the सूत्राणि पाठक्रमेण items, but ordered according to alphabets.

**Comment by kmadathil** [comment]
Fixed in 20f03c5
