### ISSUE TITLE
Duplicates in vArtikas

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#53]
There are cases in which one vArtika is mentioned in two places in SK.
See
![capture](https://cloud.githubusercontent.com/assets/5755132/23980401/525ea0aa-0a25-11e7-8d1b-1070db5c91c5.png)

It would be better to show them as comma separated items e.g.
 गतिकारकेतरपूर्वपदस्य यण्नेष्यते 272 , 281

**Comment by kmadathil** [comment]
I thought this was going to be hard, but people have walked this road before us!
http://www.jenitennison.com/xslt/grouping/muenchian.html

Fixed in 20f03c5
