### ISSUE TITLE
Update Changelog and Readme; Comment code

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#55]
# Changelog 

Currently they are mainly textual and not hyperlinked. Time to hyperlink them properly.
![capture](https://cloud.githubusercontent.com/assets/5755132/23981754/0b098d64-0a2f-11e7-99f9-0660a7addb2e.png)

# Readme

Recently many changes have happenned.
Readme has not kept pace with the changes which occurred in past one month.

# Comment code

A lot of code is currently undocumented / scarcely documented.
Now most of things are reaching finality. Time to document them in comment.

**Comment by drdhaval2785** [comment]
Will wait till @kmadathil has completed the tasks assigned to him for XSLT related stuffs, so that a new version can be launched with all such information loaded into it.

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/siddhantakaumudi/commit/68cb40713ea67da60f55bbc62b758f4e24b47ec8 made in https://github.com/drdhaval2785/siddhantakaumudi/issues/65#issuecomment-287967406 is related to this issue too. Hyperlinks and proper listing of items of change is done in that commit. 
Now majority of XSLT related items which were of urgent nature are over. 
Time to document changes since version 1.5.2 and release a new version now after making necessary changes in readme and changelog.
Code commenting is long procedure. Will remain open.

**Comment by kmadathil** [comment]
"Distributed by https://github.com/drdhaval2785/ under a GNU GPLv3 License.

https://github.com/drdhaval2785/ assumes no responsibility for unauthorised use that infringes the rights of any copyright owners, known or unknown."
@drdhaval2785 
Better to have your name here linked to the URL, is it not?

**Comment by drdhaval2785** [comment]
Changelog is now updated to include latest items, including XSLT commenting. A new release v1.8.4 is also made available https://github.com/drdhaval2785/siddhantakaumudi/releases/tag/v1.8.4.
Now next major change will start when we decide on the licencing terms as discussed in https://github.com/drdhaval2785/siddhantakaumudi/issues/22. 

If some drastic licencing change is done - we will start seeing v2.0.0 series.
Otherwise 1.9...... will continue.
