### ISSUE TITLE
Add gaNa detail in dhAtusUci

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#56]
Currently it is 
 भू सत्तायाम् 1 

Should be
 भू सत्तायाम् भ्वादिः 1 

To help you with finding the upper boundaries of 10 gaNas in SK, I have noted them in the following list
	upperbounds = [1011,1083,1107,1248,1282,1439,1464,1474,1535,1993]
i.e.
भ्वादिः - ०-१०१०
अदादिः - १०११-१०८२
जुहोत्यादिः - १०८३-११०६
दिवादिः - ११०७-१२४७
स्वादिः - १२४८-१२८१
तुदादिः - १२८२-१४३८
रुधादिः - १४३९-१४६३
तनादिः - १४६४-१४७३
क्र्यादिः - १४७४-१५३४
चुरादिः - १५३५-१९९३

So it should be possible to add भ्वादिः / अदादिः etc after a dhAtu meaning based on its number in SK.
@kmadathil I guess this should be doable.
String has to be converted to number and compared. 
No idea whether XSLT does such stuff or not.

**Comment by kmadathil** [comment]
Fixed in 36f4ffe
