### ISSUE TITLE
XSLT Needs commenting

### ISSUE THREAD

**Issue by kmadathil** [drdhaval2785/siddhantakaumudi#57]
sk_html.xslt has grown into a beast. Add comments to make it maintainable.

**Comment by drdhaval2785** [comment]
A monster already and our greed is expanding it further. Better to document
it. Otherwise after a year, refactoring your own code is harder than
writing it afresh.

**Comment by drdhaval2785** [comment]
Started taming the monster or not yet?

**Comment by kmadathil** [comment]
Incremental updates are commented. Will need to find some time to write sensible comments for the entire flow rather than commenting individual lines.

**Comment by kmadathil** [comment]
Done in 26a085d94768efbf9513bde3c2858bcc86d26c36

शुभस्य शीघ्रम्
