### ISSUE TITLE
Ignore 0-0-0 and 0-0-1 in appendices

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#59]
Ignore these two benedictory verse and shivasUtras in appendices.

(0-0-0) मंगलाचरणम्‌ 0

and

(0-0-1) अइउण्‌ । ऋलृक्‌ । एओङ्‌ । ऐऔच्‌ । हयवरट्‌ । ञमङणनम्‌ । झभञ्‌ । घढधष्‌ । जबगडदश्‌ । खफछठथचटतव्‌ । कपय्‌ । शषसर्‌ । हल्‌ । 00

Need to be removed from lists.
Needs to be removed.

**Comment by kmadathil** [comment]
Fixed in d55dc1ef
