### ISSUE TITLE
DAtukramaH tag

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#6]
Based on comments regarding DAtukramaH tag,

In future we would like to add three info at least per DAtu
1. DAtu
2. Meaning
3. DAtukramaH

Right now only point 3 is done. For some meaningful use, rest two are mandatory. Some markup enhancement or some mix of comp+manual intervention is necessary.

This issue is devoted to examination of logic.

**Comment by drdhaval2785** [comment]
1 भू सत्तायाम्।।
। 2 एध वृद्धौ ।
 3 स्पर्ध। संघर्षे।
 6 नाथृ 7 नाधृ याच्ञ्ञोपतापैस्वर्याशीःषु।।
 43 कुथि 44 पुथि 45 लुथि 46 मथि हिंसासंक्लेशनयोः।

**Comment by gasyoun** [comment]
What list do you want to take for the base? arthas are different in number, you know that.

**Comment by drdhaval2785** [comment]
On 3 Feb 2017 20:32, "Marcis Gasuns" <notifications@github.com> wrote:

What list do you want to take for the base? arthas are different in number,
you know that.


I know the intricacies involved in DAtus. This will be based on the verbs
inumerated in SK itself. Not based on any external list. I dont intend to
separate three arthas into three different parts. One tag having the text
of three arthas will suffice.

The problem is twofold. Many verbs have same meaning and a single verb has
many meanings.

**Comment by kmadathil** [comment]
Wherever the dhatu and meaning follow the tag, they can be extacted. For example, the index in my fork has 
अक 792
अकि लक्षणे 87
अक्षू व्याप्तौ 654
अग कुटिलायां गतौ 793
अगद नीरोगत्वे 1987
etc., all automatically extracted from the xml

However, where the meaning isn't present, we need a better way of matching in a standard dhatupaaTha version, maybe?
eg:
अगि 146
अघि 109

**Comment by drdhaval2785** [comment]
Created a separate branch verbdata for this feature.
regex `'। [0-9]{1,4} [^ ]+ [^।]+।'` in sk0.txt seems to capture this detail well.
https://github.com/drdhaval2785/siddhantakaumudi/blob/verbdata/verbdata.txt is the file which has extracted the details of verb. 

There are a few entries missing there. Manual examination of verbdata.txt and corrections in sk0.txt will help to fill the gap.

**Comment by drdhaval2785** [comment]
Missing items
69, 240, 241, 244, 246-251, 272, 284, 285, 307, 309, 310, 312, 314, 316, 318, 319, 320, 322, 325, 327-329, 333, 340, 344, 347, 356, 357, 374, 380, 383, 385, 400, 403, 440, 443, 461, 462, 483, 491, 492,

**Comment by drdhaval2785** [comment]
Did a fresh job over these verbs.
verbdata branch was dedicated to it.
Now it is merged with master branch.
@kmadathil 
Typical dhAtu line is something like this.
This may help you capture the details for HTML
`div type="dhātvarthaḥ"` captures a list of verbs for single meaning.
It has children `div type="dhātuḥ"` which has the following text `verbnumber verb` separated by a space.

```
<div type="dhātvarthaḥ"> <div type="dhātuḥ">1267 तिक</div> <div type="dhātuḥ">1268 तिग</div> गतौ च</div
```
for multiple verbs in single meaning
and
```
<div type="dhātvarthaḥ"> <div type="dhātuḥ">1 भू</div> सत्तायाम्</div>
```
for one verb in single meaning.

You may need to modify your XSLT and regenerate HTML etc based on this new sk.xml file.

**Comment by drdhaval2785** [comment]
I have changed the line `<h2 class="index">धतुसूचि: (संगणितः)</h2>` of xslt to `<h2 class="index">धातुसूचि: (संगणितः)</h2>`.
धतु -> धातु
You may also like to change your local xslt based on it or git pull.

**Comment by kmadathil** [comment]
Thanks for the typo fix.
I have updated the dhatu index.

**Comment by drdhaval2785** [comment]
@kmadathil 

I see that currently the verb is mentioned as `<span id="D1108"><b>षिवु</b></span>तन्तुसन्ताने`
I feel that HTML should also show the number of verb.
That would give the user idea about where he has reached.

`<span id="D1108">1108 <b>षिवु</b></span> तन्तुसन्ताने` would be better for visual importance as the base text also has those numbers written.
