### ISSUE TITLE
Abnormal vArtikas - identified by sorting

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#61]
(ग)अन्तरं बहिर्योगेति गणसूत्रेऽपुरीति वक्तव्यम् 217
(ग.) तद्बृहतोः करपत्योश्चोरदेवतयोः सुट् तलोपश्च 1071
??जमेर्बुक्‌ ?? उ93
?अग्रग्रामाभ्यां नयतेर्णो वाच्यः (अा) ? 2975
?अवहाराधारावायानामुपसङ्ख्यानम्? 3301
?ईहायामेव? 2691
?कमेर्बुक्‌ च (ग) ? उ106
?कर्मणि समि च (अा) ? 2966
?किब्वचिप्रच्छयायतस्तुकटप्रुजुश्रीणं दीर्घोऽसंप्रसारणं च? 3158
?कुटिकशिकौतिभ्यः प्रत्ययस्य मुट्‌ च (ग) ? उ106
?कोकतेर्वा कुक्‌ च (ग) ? उ41
?कौतेर्नुम्‌ च (ग) ? उ538
?छन्दसीति वक्तव्यम्? 2869
?धर्मादिष्वनियमः (अा) ? 902
?फल्गुन्यषाढाभ्यां टानौ वक्तव्यौ (वा)अ ? 1408
?लङ्गेर्वृद्धिश्च (ग) ? उ106
?वेर्ग्रो वक्तव्यः (अा) ? 859
?शमेर्बुक्‌ च (ग) ? उ481
?शीलिकामिभक्ष्याचरिभ्यो णः (वाअ) ? 2913
?सहायाद्वा (अा) ? 1797
?सृजियुज्योः श्यंस्तु ? 2769
?हिमाच्चेलुः? 1928 
 ृशोरग्वक्तव्यः 3434

**Comment by drdhaval2785** [comment]
Majority corrected.
Will revisit after regeneration of HTML from corrected XML.

**Comment by kmadathil** [comment]
Regenerated

**Comment by drdhaval2785** [comment]
Rechecked.
All abnormals vanished.
