### ISSUE TITLE
Abnormal verbs - identified by sorting

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#62]
(ग) शमो दर्शने भ्वादिः 818
(ग) चर्करीतं च अदादिः 1081 

 ॠ गतौ क्र्यादिः 1498 is sorted after even 'h'.
Sorting error inherent to character encoding.

**Comment by drdhaval2785** [comment]
First two corrected.

Third is something which @kmadathil will have to handle.

**Comment by kmadathil** [comment]
Same issue with sUtra: (7-1-100) ॠत इद्धातोः 2390

These were due to Unicode encoding ॠ in the wrong place, which complicates lexicographical sort. A custom workaround using a multi-stage sort was implemented in both cases.  

Both have been fixed in d712340d92917ed0dc8bfdbe6ee068199d097376

**Comment by gasyoun** [comment]
> These were due to Unicode encoding ॠ in the wrong place

Yeah, a known issue. Dhaval has solved it in the past as well.
