### ISSUE TITLE
Revision history `\n` to `<br/>`

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#65]
Revision history in XML is written for text editors, so has line breaks.
Whereas when we show it in HTML, it makes sense to have 'br'.
This will ensure that all the points are on new line.
![capture](https://cloud.githubusercontent.com/assets/5755132/24114483/6d4bde92-0dc6-11e7-9dba-443c9f084cf5.png)

**Comment by kmadathil** [comment]
@drdhaval2785 
Since the input is generated by us, it would be more in the spirit of XML to encode the structure,  like this.
```
<change who="Dr. Dhaval Patel" when="2016-12-27"> 1.0.0 - First version. 
<list rend='numbered'>
<item> There are misorders in this file. So created a list of misordered sUtra numbers by step0.py in step0_notes.txt and made corrections in sk0.txt. </item> 
<item> Added missing 2139-2150 sUtras manually in sk0.txt. </item>
...
</list>
</change>

```
Also, we can use `<p></p>` to delimit text that needs to start with a new line within the change description. 

I will modify the XSLT to introduce the required HTML formatting based on this.

**Comment by drdhaval2785** [comment]
Fair proposal. Will do so and let you know.

**Comment by drdhaval2785** [comment]
Corrected this. 
There are minor changes in XML along with this. `version` tag holds version number.
`a href` holds links just like in HTML.

```
<change who="Karthikeyan Madathil" when="2017-02-12">
<version>1.1.1</version>
<list rend="numbered">
<item>Added sUtra detail on mouse hover.</item>
<item>External links open in new tab.</item>
<item>Latest HTML file is hosted <a href="https://drdhaval2785.github.io/siddhantakaumudi">here</a> for online viewing.</item>
</list> 
</change>
```

**Comment by kmadathil** [comment]
Done in 4e0bd53

@drdhaval2785 
`<a href= ..` should have been `<target ref=...` according to TEI encoding. I've taking the liberty of making the change in make_xml.py and regenerating xml too. Please revert my changes I've messed something up.

**Comment by drdhaval2785** [comment]
Closing.
