### ISSUE TITLE
Change the sutra links to https://ashtadhyayi.com/sutraani/

### ISSUE THREAD

**Issue by chandrasekharanr** [drdhaval2785/siddhantakaumudi#70]
The sutras now point to avg-sanskrit sutra pages. Please change the links to https://ashtadhyayi.github.io/ sutra pages.

**Comment by drdhaval2785** [comment]
Ok.

**Comment by gasyoun** [comment]
> Ok.

Relinked?

**Comment by drdhaval2785** [comment]
Now the best frontend seems to be https://ashtadhyayi.com/sutraani/1/1/1
Will change to ashtadhyayi.com site.

**Comment by drdhaval2785** [comment]
@kmadathil 
As you were the one who wrote the code for xslt, would it be possible for you to rewrite the xslt to link to ashtadhyayi.com now?
I would appreciate a pull request.

https://github.com/drdhaval2785/siddhantakaumudi/blob/b22f625ef608ca60abe8a42eb04c5740baffe785/sk_html.xslt#L404  would require some tweaking to point from existing https://avg-sanskrit.org/sutras/1-2-27.html to desired https://ashtadhyayi.com/sutraani/1/2/27 for example.

**Comment by kmadathil** [comment]
Thankfully, I've noticed in an earlier context that ashtadhyayi.com backend allows multiple link syntaxes. I'll just change to [https://ashtadhyayi.com/sutraani/1-2-27](https://ashtadhyayi.com/sutraani/1-2-27)
