### ISSUE TITLE
Typo in SK294

### ISSUE THREAD

**Issue by kmadathil** [drdhaval2785/siddhantakaumudi#71]
294: व्रश्चभ्रस्जसृजमृजयजराजभ्राजच्छशां षः (8-2-36)

व्रश्चादीनां सप्तानां छशान्तयोश्च वकारोऽन्तादेशः स्याज्झलि पदान्ते च । 

Shouldn't that be षकारोऽन्तादेशः? I found the same typo in [Ashtadhyayi.com](https://ashtadhyayi.com/sutraani/8/2/36), who may have used this, or a common source.

SC Vasu has षकारो

**Comment by drdhaval2785** [comment]
Right. Will correct.

**Comment by gasyoun** [comment]
> Will correct.

Done?
