### ISSUE TITLE
Make XML TEI compliant

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/siddhantakaumudi#9]
In response to posting this XML on Indology group, one of the suggestion was to make it TEI compliant by adding header information regarding digitization and revision history, responsibility etc.

It seems a decent and easily doable thing.
XSLT and subsequent steps may have to be refactored to account for changed XPATH.

**Comment by drdhaval2785** [comment]
@kmadathil 
Would it be possible for you to modify XSLT if I change the tags according to TEI guidelines. I am not sure about how to do it.

Dominik Wujastyk mentioned the following in response to SK XML publication.

>It's wonderful that you've done all the tagging for the <i>Siddhantakaumudi</i>.&nbsp; But there is no document header, so the reader has no idea what the text is, historically.&nbsp; Which edition is the etext derived from?&nbsp; What changes have been made?&nbsp; In other words, pedigree and version history.&nbsp; I note your suggestion about the Trichinopoly edition.</div><div class="gmail_default" style="font-family:trebuchet ms,sans-serif;font-size:small"><br></div><div class="gmail_default" style="font-family:trebuchet ms,sans-serif;font-size:small">All these points are addressed by the formalism of the <a href="http://www.tei-c.org/About/Archive_new/ETE/Preview/index.xml" target="_blank" data-saferedirecturl="https://www.google.com/url?hl=en&amp;q=http://www.tei-c.org/About/Archive_new/ETE/Preview/index.xml&amp;source=gmail&amp;ust=1486444946756000&amp;usg=AFQjCNFZytadsnlpZ1QnAAnfQx2z5fmj8w">Text Encoding Initiative</a>, and in particular the TEI header.&nbsp; If I may suggest it, it would be of great value to the indological community at large and for future researchers if a text such as your SK were encoded using the TEI guidelines. &nbsp;</div><div class="gmail_default" style="font-family:trebuchet ms,sans-serif;font-size:small"><br></div><div class="gmail_default" style="font-family:trebuchet ms,sans-serif;font-size:small">Even <i>formally</i> encoding the fact that the source of the etext is uncertain is valuable.</div><div class="gmail_default" style="font-family:trebuchet ms,sans-serif;font-size:small"><br></div><div class="gmail_default" style="font-family:trebuchet ms,sans-serif;font-size:small">The <a href="http://sarit.indology.info" target="_blank" data-saferedirecturl="https://www.google.com/url?hl=en&amp;q=http://sarit.indology.info&amp;source=gmail&amp;ust=1486444946756000&amp;usg=AFQjCNHO0xghZzzx544tTD9GBMj752cYVA">SARIT</a> library would be delighted to include your SK etext, but we cannot do so until it is encoded to the TEI standard, according to our <a href="http://sarit.indology.info/exist/apps/sarit/docs/encoding-guidelines-simple.html" target="_blank" data-saferedirecturl="https://www.google.com/url?hl=en&amp;q=http://sarit.indology.info/exist/apps/sarit/docs/encoding-guidelines-simple.html&amp;source=gmail&amp;ust=1486444946756000&amp;usg=AFQjCNEnntgdrC_wHPTa2f22J_G6zUDuFA">simplified SARIT guidelines</a>. &nbsp;</div><div class="gmail_default" style="font-family:trebuchet ms,sans-serif;font-size:small"><br></div><div class="gmail_default" style="font-family:trebuchet ms,sans-serif;font-size:small">Incidentally, SARIT also stores all its texts <a href="https://github.com/sarit/SARIT-corpus/" target="_blank" data-saferedirecturl="https://www.google.com/url?hl=en&amp;q=https://github.com/sarit/SARIT-corpus/&amp;source=gmail&amp;ust=1486444946756000&amp;usg=AFQjCNHAqBhdiTO7CP756phWC1hwXQ8OQw">in Github</a>.</div><div class="gmail_default" style="font-family:trebuchet ms,sans-serif;font-size:small"><br></div><div class="gmail_default" style="font-family:trebuchet ms,sans-serif;font-size:small">Best wishes,</div><div class="gmail_default" style="font-family:trebuchet ms,sans-serif;font-size:small"><span class="il">Dominik</span> Wujastyk</div>

**Comment by kmadathil** [comment]
Yes, I can make the XSLT changes.

**Comment by gasyoun** [comment]
> XSLT change

Great, Dominik is one of the the editors at TEI, so he will not advice a bad thing.

**Comment by drdhaval2785** [comment]
@kmadathil 
Currently tag changing for making XML TEI compliant is undergoing.
When it is finished, I will post here so that you may start your XSLT updation.

**Comment by drdhaval2785** [comment]
@kmadathil 

I guess the text is more or less TEI / SARIT compliant.
Major items worth noting for modification of XSLT would be
1. `TEI` element is root with two children `teiHeader` and `text`.
2. `teiHeader` has information regarding various metadata items.
3. `text` has only one child `body`.
4. `body` has children `div type="prakaraṇa"` which stand for prakaraṇa of the book.
5. Every `div type="prakaraṇa"` has three members - 1. `head` e.g. `<head>॥ अथ संज्ञाप्रकरणम्‌ ॥</head>`. 2. A repeated tag of `div type="sūtra_with_explanation"` (explained below). 3. `trailer` e.g. `<trailer>। इति संज्ञाप्रकरणम्‌ ।</trailer>`
6. A typical sUtra with explanation looks like this
```
<div type="sūtra_with_explanation" n="1">
<ab type="sūtra" n="1"><label type="SK">1</label><label type="AS">1-3-3</label> हलन्त्यम् </ab>
<p>
हल् (मा.सू.-<div type="SKsandarbhaH">14</div>) इति सूत्रेऽन्त्यमित्स्यात् ।
</p>
</div>
```
7. In the above item `n` stands for sUtra number in SK. `ab type="sūtra"` stands for abstract block (sUtra details). `label type="SK"` stands for the sUtra number in SK. `label type="AS" stands for sUtra number in AS. And the text ` हलन्त्यम् ` stands for the sUtra text. `p` stands for explanation of Bhattoji Dikshita. 
8. Other tags are `div type="SKsandarbhaḥ" - for internal SK references. `div type="dhātukramaḥ"` - for dhAtu numbers. `div type="vārtika` - for vArtika.

I think there will be some minor modifications later on based on feedback from SARIT people. 
For now, the sk.xml may be treated as stable and your changes may be merged based on it.


1. <div type="prakaraṇa"> encloses one chapter.

**Comment by kmadathil** [comment]
Changes made.
